export default {
    FETCHING_DATA: 'FETCHING_DATA',
    FETCHING_DATA_SUCCESS: 'FETCHING_DATA_SUCCESS',
    FETCHING_DATA_FAILURE: 'FETCHING_DATA_FAILURE',
    OPEN_PHOTO: 'OPEN_PHOTO',
    UNSPLASH_URL: 'https://api.unsplash.com/photos/',
    NUMBER_COLUMNS: 3
}